version: "3.8"

services:
  node3:
    image: pvl/blockchain
    container_name: node3
    environment:
      - SERVER_ID=3
      - SERVER_HOST=node3:5002
      - NEIGHBOURS=node1:5000,node2:5001
    tty: true


  node2:
    image: pvl/blockchain
    container_name: node2
    environment:
      - SERVER_ID=2
      - SERVER_HOST=node2:5001
      - NEIGHBOURS=node1:5000,node3:5002
    tty: true

  node1:
    image: pvl/blockchain
    container_name: node1
    environment:
      - SERVER_ID=1
      - SERVER_HOST=node1:5000
      - NEIGHBOURS=node2:5001,node3:5002
    tty: true
    depends_on:
      - node2
      - node3